### PR TITLE
TravisCI configured to deploy to the official GDG Kolachi Firebase Project.

### PR DESCRIPTION
**Pull request by nawazishali**
I have configured the TravisCI to deploy to the official website, The secure key still needs to be changed for TravisCI to work properly, Also this repo needs to be set to watch mode on Travis Dashboard. Just let me know if there is anything else to be done.

### CODE REVIEW

**Comment by mashhoodr** [comment]
@ericbhatti we need a GDGKolachi (free) account on TravisCI and its key so we can add this there. @nawazishali have you configure the correct Firebase account (one Eric shared with us?)

**Comment by nawazishali** [comment]
I have readonly access to the firebase project shared by @ericbhatti . Kindly provide full access along with Travis CI key so that I can set this up for V2 branch.

**Comment by ericbhatti** [comment]
@nawazishali access granted on Firebase. Project setup on TravisCI too: https://travis-ci.org/GDGKolachi/hoverboard/

**Comment by nawazishali** [comment]
@ericbhatti  Thanks, Will be making a pull request here shortly.

**Comment by mashhoodr** [comment]
@nawazishali can this PR be closed?

**Comment by nawazishali** [comment]
@mashhoodr Yes this PR can be closed safely.

**Pull request closed without merging**
