### PR TITLE
Sarah/issue 14

### LINKED ISSUE #14: Schedule should also show speakers for the session
If a session has speakers, the schedule list, should show the speakers against that session. The speaker's photo, name, and organization should be shown. If a session has multiple speakers, each speaker will be shown in a new line. The speaker's name will be clickable and the user will be routed to the main speakers page where the selected speaker's popup is shown.

### PR DESCRIPTION
**Pull request by sarahsga**
fixes #14

### CODE REVIEW

**Comment by mashhoodr** [comment]
@nawazishali can you please review this

**Comment by nawazishali** [comment]
@mashhoodr sure.

**Comment by nawazishali** [comment]
@sarahsga  Unfortunately this PR is of no use as we are currently working on branch hoverboard-v2 and this PR is from master branch. @mashhoodr We will need to add a contribution guideline in the repo so that new PR's don't get wasted like this. Current ReadME and guidelines are related to Official GDG devfest ukraine repo. We can open another issue for someone to update the guide I guess.

**Comment by mashhoodr** [comment]
ah crap. Sorry @sarahsga i forgot to mention this. @nawazishali im making the hover2 branch as default and removing the others. Can you please update the readme for that likewise.

**Comment by ericbhatti** [comment]
@mashhoodr Can we move our code to a separate branch altogether hoverboard-v2-kolachi and treat it as our main branch?

**Comment by nawazishali** [comment]
@mashhoodr  Sure, I will update the readme today.

**Comment by sarahsga** [comment]
@mashhoodr no problem. Will continue looking for issues once contribution guidelines have been added.

**Comment by mashhoodr** [comment]
@sarahsga they are added now. closing this one.

**Pull request closed without merging**
